name: release

on:
  release:
    types: [published]
    
jobs:
  build:
    uses: ./.github/workflows/docker-image.yml 
    secrets: inherit
    
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Copy file
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: "docker-compose.prod.yaml"
          target: "./"
      - name: Restart daemon
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            mv docker-compose.prod.yaml docker-compose.yaml 
            docker-compose pull 
            docker-compose up -d